---

- name: grafana | Ensure apt key for grafana is present
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: grafana | Ensure grafana repo is added
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: grafana | install package
  apt:
    name: grafana
    state: latest

- name: grafana | Enable service and start
  service:
    name: grafana-server
    enabled: yes
    state: started