---

- name: grafana | Ensure apt key for grafana is present
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present

- name: grafana | Ensure grafana repo is added
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: grafana | install package
  apt:
    name: grafana
    state: latest

- name: grafana | Enable service and start
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: Check for custom nginx config
  local_action: stat path="{{playbook_dir}}/user-settings/grafana.conf.j2"
  become: False
  register: grafana_custom_nginx_file

- name: Create nginx config with default template
  template:
    src: "{{playbook_dir}}/user-settings/grafana.conf.j2.dist"
    dest: /etc/nginx/sites-available/grafana.conf
  when: grafana_custom_nginx_file.stat.exists == false

- name: Create nginx config with custom file
  template:
    src: "{{playbook_dir}}/user-settings/grafana.conf.j2"
    dest: /etc/nginx/sites-available/grafana.conf
  when: grafana_custom_nginx_file.stat.exists