---

nginx_remove_default_vhost: true
nginx_worker_processes: "2"
nginx_worker_connections: "2048"

nginx_sendfile: "on"
nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"
nginx_client_max_body_size: "64m"