---

- name: Upgrade repository
  apt: upgrade=dist force=yes autoclean=yes autoremove=yes

- name: check custom hosts file
  local_action: stat path="{{playbook_dir}}/user-settings/hosts"
  become: False
  register: custom_hosts_file

- hostname:
    name: "{{base_hostname}}"

- name: copy files
  template: src={{item.path}} dest={{item.dest}} mode={{item.mode}} owner={{item.owner}} group={{item.group}}
  with_items:
    - { path: 'hosts.j2', dest: '/etc/hosts', owner: root, group: root, mode: 644 }
    - { path: 'motd.j2', dest: '/etc/update-motd.d/01-diomedes-logo', owner: root, group: root, mode: 750 }

- name: Disallow password authentication
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh

- name: overwrite hosts if custom file is present
  copy: src={{playbook_dir}}/user-settings/hosts dest=/etc/hosts mode=644 owner=root group=root
  when: custom_hosts_file.stat.exists == True

- name: install syspackages
  apt:
    state: latest
    name:
      #- update-motd
      - screen
      - cifs-utils
      - telnet
      - apt-transport-https
      - logrotate
      - vim
      - curl
      - git
      - git-core
      - restic
      - screen
      - sysstat
      - sshfs
      - build-essential
      - wget
      - bash-completion
      - ntp
      - ntpdate
      - unzip
      - bzip2
      - zip
      - p7zip-full
      - unrar-free
      - arj
      - samba
      - samba-common
      - smbclient
      - python3
      - python3-pip
      - python3-dev
      - python3-mysqldb
      - zsh
      - powerline
      - fonts-powerline

- name: check if oh-my-zsh is already installed
  stat: 
    path: "/root/.oh-my-zsh"
  register: oh_my_zsh_dir

- name: Clone oh-my-zsh repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /root/.oh-my-zsh
  when:
    - user_enable_zsh == True
    - oh_my_zsh_dir.stat.exists == False

- name: set zsh shell as default
  user:
    name: root
    shell: /bin/zsh
    append: yes # check - deprecated
  when: user_enable_zsh == True

- name: set bash shell as default
  user:
    name: root
    shell: /bin/bash
    append: yes # check - deprecated
  when: user_enable_zsh == False